import { Kanji } from "../../model/Kanji";

export const chapter10: Kanji[] = [
    { kanji: '木', onyomi: 'ボク', kunyomi: 'き', meaning: 'tree' },
    { kanji: '林', onyomi: 'リン', kunyomi: 'はやし', meaning: 'grove' },
    { kanji: '森', onyomi: 'シン', kunyomi: 'もり', meaning: 'forest' },
    { kanji: '桂', onyomi: 'ケイ', kunyomi: 'かつら', meaning: 'Japanese Judas-tree' },
    { kanji: '柏', onyomi: 'ハク', kunyomi: 'かしわ', meaning: 'oak' },
    { kanji: '枠', onyomi: 'わく', kunyomi: '', meaning: 'frame' },
    { kanji: '梢', onyomi: 'ショウ', kunyomi: 'こずえ', meaning: 'treetops' },
    { kanji: '棚', onyomi: 'とう', kunyomi: 'たな', meaning: 'shelf' },
    { kanji: '杏', onyomi: 'キョウ', kunyomi: 'あんず', meaning: 'apricot' },
    { kanji: '桐', onyomi: 'トウ', kunyomi: 'きり', meaning: 'paulownia' },
    { kanji: '植', onyomi: 'ショク', kunyomi: 'う-える', meaning: 'plant' },
    { kanji: '椅', onyomi: 'イ', kunyomi: 'いす', meaning: 'chair' },
    { kanji: '枯', onyomi: 'コ', kunyomi: 'か-れる', meaning: 'wither' },
    { kanji: '朴', onyomi: 'ボク', kunyomi: 'ほう', meaning: 'crude' },
    { kanji: '村', onyomi: 'ソン', kunyomi: 'むら', meaning: 'village' },
    { kanji: '相', onyomi: 'ソウ', kunyomi: 'あい', meaning: 'inter-' },
    { kanji: '机', onyomi: 'キ', kunyomi: 'つくえ', meaning: 'desk' },
    { kanji: '本', onyomi: 'ホン', kunyomi: 'もと', meaning: 'book' },
    { kanji: '札', onyomi: 'サツ', kunyomi: 'ふだ', meaning: 'tag' },
    { kanji: '暦', onyomi: 'レキ', kunyomi: 'こよみ', meaning: 'calendar' },
    { kanji: '案', onyomi: 'アン', kunyomi: 'つくえ', meaning: 'plan' },
    { kanji: '燥', onyomi: 'ソウ', kunyomi: '', meaning: 'parch' },
    { kanji: '未', onyomi: 'ミ', kunyomi: 'いま-だ', meaning: 'not yet' },
    { kanji: '末', onyomi: 'マツ', kunyomi: 'すえ', meaning: 'extremity' },
    { kanji: '昧', onyomi: 'マイ', kunyomi: 'まぶ-しい', meaning: 'obscure' },
    { kanji: '沫', onyomi: 'マツ', kunyomi: 'あわ', meaning: 'splash' },
    { kanji: '味', onyomi: 'ミ', kunyomi: 'あじ', meaning: 'flavor' },
    { kanji: '妹', onyomi: 'マイ', kunyomi: 'いもうと', meaning: 'younger sister' },
    { kanji: '朱', onyomi: 'シュ', kunyomi: 'あけ', meaning: 'vermilion' },
    { kanji: '株', onyomi: 'シュ', kunyomi: 'かぶ', meaning: 'stocks' },
    { kanji: '若', onyomi: 'ジャク', kunyomi: 'わか-い', meaning: 'young' },
    { kanji: '草', onyomi: 'ソウ', kunyomi: 'くさ', meaning: 'grass' },
    { kanji: '苦', onyomi: 'ク', kunyomi: 'くる-しい', meaning: 'suffering' },
    { kanji: '苛', onyomi: 'カ', kunyomi: 'いじ-める', meaning: 'bullying' },
    { kanji: '寛', onyomi: 'カン', kunyomi: 'くつろ-ぐ', meaning: 'tolerant' },
    { kanji: '薄', onyomi: 'ハク', kunyomi: 'うす-い', meaning: 'dilute' },
    { kanji: '葉', onyomi: 'ヨウ', kunyomi: 'は', meaning: 'leaf' },
    { kanji: '模', onyomi: 'モ', kunyomi: '', meaning: 'imitation' },
    { kanji: '漠', onyomi: 'バク', kunyomi: 'ばく', meaning: 'vague' },
    { kanji: '墓', onyomi: 'ボ', kunyomi: 'はか', meaning: 'grave' },
    { kanji: '暮', onyomi: 'ボ', kunyomi: 'く-れる', meaning: 'livelihood' },
    { kanji: '膜', onyomi: 'マク', kunyomi: '', meaning: 'membrane' },
    { kanji: '苗', onyomi: 'ビョウ', kunyomi: 'なえ', meaning: 'seedling' }
];
