import { Kanji } from "../../model/Kanji";

export const chapter15: Kanji[] = [
    { kanji: '学', onyomi: 'ガク', kunyomi: 'まな-ぶ', meaning: 'study' },
    { kanji: '覚', onyomi: 'カク', kunyomi: 'おぼ-える', meaning: 'memorize' },
    { kanji: '栄', onyomi: 'エイ', kunyomi: 'さか-える', meaning: 'flourish' },
    { kanji: '書', onyomi: 'ショ', kunyomi: 'か-く', meaning: 'write' },
    { kanji: '津', onyomi: 'シン', kunyomi: 'つ', meaning: 'haven' },
    { kanji: '牧', onyomi: 'ボク', kunyomi: 'まき', meaning: 'breed' },
    { kanji: '攻', onyomi: 'コウ', kunyomi: 'せ-める', meaning: 'aggression' },
    { kanji: '敗', onyomi: 'ハイ', kunyomi: 'やぶ-れる', meaning: 'failure' },
    { kanji: '枚', onyomi: 'マイ', kunyomi: 'はい', meaning: 'a sheet of' },
    { kanji: '故', onyomi: 'コ', kunyomi: 'ゆえ', meaning: 'happenstance' },
    { kanji: '敬', onyomi: 'ケイ', kunyomi: 'うやま-う', meaning: 'awe' },
    { kanji: '言', onyomi: 'ゲン', kunyomi: 'い-う', meaning: 'say' },
    { kanji: '警', onyomi: 'ケイ', kunyomi: 'いまし-める', meaning: 'admonish' },
    { kanji: '計', onyomi: 'ケイ', kunyomi: 'はか-る', meaning: 'plot' },
    { kanji: '詮', onyomi: 'セン', kunyomi: 'せん-べん', meaning: 'elucidate' },
    { kanji: '獄', onyomi: 'ゴク', kunyomi: 'とりで', meaning: 'prison' },
    { kanji: '訂', onyomi: 'テイ', kunyomi: 'ただ-す', meaning: 'revise' },
    { kanji: '訃', onyomi: 'フ', kunyomi: 'しら-せる', meaning: 'obituary' },
    { kanji: '討', onyomi: 'トウ', kunyomi: 'う-つ', meaning: 'chastise' },
    { kanji: '訓', onyomi: 'クン', kunyomi: 'おし-える', meaning: 'instruction' },
    { kanji: '詔', onyomi: 'ショウ', kunyomi: '', meaning: 'imperial edict' },
    { kanji: '詰', onyomi: 'キツ', kunyomi: 'つ-める', meaning: 'packed' },
    { kanji: '話', onyomi: 'ワ', kunyomi: 'はな-す', meaning: 'tale' },
    { kanji: '詠', onyomi: 'エイ', kunyomi: 'よ-む', meaning: 'recitation' },
    { kanji: '詩', onyomi: 'シ', kunyomi: 'うた', meaning: 'poem' },
    { kanji: '語', onyomi: 'ゴ', kunyomi: 'かた-る', meaning: 'word' },
    { kanji: '読', onyomi: 'ドク', kunyomi: 'よ-む', meaning: 'read' },
    { kanji: '調', onyomi: 'チョウ', kunyomi: 'しら-べる', meaning: 'tune' },
    { kanji: '談', onyomi: 'ダン', kunyomi: '', meaning: 'discuss' },
    { kanji: '諾', onyomi: 'ダク', kunyomi: '', meaning: 'consent' },
    { kanji: '諭', onyomi: 'ユ', kunyomi: 'さと-す', meaning: 'rebuke' },
];
