export const chapter18c = [
    { kanji: '鐘', onyomi: 'ショウ', kunyomi: 'かね', meaning: 'bell' },
    { kanji: '商', onyomi: 'ショウ', kunyomi: 'あきな-う', meaning: 'make a deal' },
    { kanji: '嫡', onyomi: 'チャク', kunyomi: '-', meaning: 'legitimate wife' },
    { kanji: '適', onyomi: 'テキ', kunyomi: 'かな-う', meaning: 'suitable' },
    { kanji: '滴', onyomi: 'テキ', kunyomi: 'しずく, したた-る', meaning: 'drip' },
    { kanji: '敵', onyomi: 'テキ', kunyomi: 'かたき', meaning: 'enemy' },
    { kanji: '匕', onyomi: 'ヒ', kunyomi: '-', meaning: 'spoon' },
    { kanji: '叱', onyomi: 'シツ', kunyomi: 'しか-る', meaning: 'scold' },
    { kanji: '匂', onyomi: 'ヒ', kunyomi: 'にお-う', meaning: 'aroma' },
    { kanji: '頃', onyomi: 'ケイ', kunyomi: 'ころ', meaning: 'about that time' },
    { kanji: '北', onyomi: 'ホク', kunyomi: 'きた', meaning: 'north' },
    { kanji: '背', onyomi: 'ハイ', kunyomi: 'せ, せい', meaning: 'stature' },
    { kanji: '比', onyomi: 'ヒ', kunyomi: 'くら-べる', meaning: 'compare' },
    { kanji: '昆', onyomi: 'コン', kunyomi: '-', meaning: 'descendants' },
    { kanji: '皆', onyomi: 'カイ', kunyomi: 'みな', meaning: 'all' },
    { kanji: '楷', onyomi: 'カイ', kunyomi: '-', meaning: 'block letters' },
    { kanji: '諧', onyomi: 'カイ', kunyomi: '-', meaning: 'orderliness' },
    { kanji: '混', onyomi: 'コン', kunyomi: 'ま-じる, ま-ざる, ま-ぜる, こ-む', meaning: 'mix' },
    { kanji: '渇', onyomi: 'カツ', kunyomi: 'かわ-く', meaning: 'thirst' },
    { kanji: '謁', onyomi: 'エツ', kunyomi: '-', meaning: 'audience' },
    { kanji: '褐', onyomi: 'カツ', kunyomi: '-', meaning: 'brown' },
    { kanji: '喝', onyomi: 'カツ', kunyomi: '-', meaning: 'hoarse' },
    { kanji: '葛', onyomi: 'カツ', kunyomi: 'くず', meaning: 'kudzu' },
    { kanji: '旨', onyomi: 'シ', kunyomi: 'むね', meaning: 'delicious' }
];
