export const chapter18a = [
    { kanji: '衣', onyomi: 'イ', kunyomi: 'ころも', meaning: 'garment' },
    { kanji: '裁', onyomi: 'サイ', kunyomi: 'た-つ', meaning: 'tailor' },
    { kanji: '装', onyomi: 'ソウ', kunyomi: 'よそお-う', meaning: 'attire' },
    { kanji: '裏', onyomi: 'リ', kunyomi: 'うら', meaning: 'back' },
    { kanji: '壊', onyomi: 'カイ', kunyomi: 'こわ-す', meaning: 'demolition' },
    { kanji: '哀', onyomi: 'アイ', kunyomi: 'あわ-れ', meaning: 'pathetic' },
    { kanji: '遠', onyomi: 'エン', kunyomi: 'とお-い', meaning: 'distant' },
    { kanji: '猿', onyomi: 'エン', kunyomi: 'さる', meaning: 'monkey' },
    { kanji: '初', onyomi: 'ショ', kunyomi: 'はじ-め', meaning: 'first time' },
    { kanji: '巾', onyomi: 'キン', kunyomi: 'はば', meaning: 'towel' },
    { kanji: '布', onyomi: 'フ', kunyomi: 'ぬの', meaning: 'linen' },
    { kanji: '帆', onyomi: 'ハン', kunyomi: 'ほ', meaning: 'sail' },
    { kanji: '幅', onyomi: 'フク', kunyomi: 'はば', meaning: 'hanging scroll, asdasdasdaasd' },
    { kanji: '帽', onyomi: 'ボウ', kunyomi: 'ずきん', meaning: 'cap' },
    { kanji: '幕', onyomi: 'マク', kunyomi: 'とばり', meaning: 'curtain' },
    { kanji: '幌', onyomi: 'コウ', kunyomi: 'ほろ', meaning: 'canopy' },
    { kanji: '錦', onyomi: 'キン', kunyomi: 'にしき', meaning: 'brocade' },
    { kanji: '市', onyomi: 'シ', kunyomi: 'いち', meaning: 'market' },
    { kanji: '柿', onyomi: 'シ', kunyomi: 'かき', meaning: 'persimmon' },
    { kanji: '姉', onyomi: 'シ', kunyomi: 'あね', meaning: 'elder sister' },
    { kanji: '肺', onyomi: 'ハイ', kunyomi: 'はい', meaning: 'lungs' },
];
export const chapter18b = [
    { kanji: '帯', onyomi: 'タイ', kunyomi: '-', meaning: 'sash' },
    { kanji: '滞', onyomi: 'タイ', kunyomi: 'とどこお-る', meaning: 'stagnate' },
    { kanji: '刺', onyomi: 'シ', kunyomi: 'さ-す, さ-さる', meaning: 'thorn' },
    { kanji: '制', onyomi: 'セイ', kunyomi: '-', meaning: 'system' },
    { kanji: '製', onyomi: 'セイ', kunyomi: '-', meaning: 'made in...' },
    { kanji: '転', onyomi: 'テン', kunyomi: 'ころ-がる, ころ-げる', meaning: 'revolve' },
    { kanji: '芸', onyomi: 'ゲイ', kunyomi: '-', meaning: 'technique' },
    { kanji: '雨', onyomi: 'ウ', kunyomi: 'あめ, あま-', meaning: 'rain' },
    { kanji: '雲', onyomi: 'ウン', kunyomi: 'くも', meaning: 'cloud' },
    { kanji: '曇', onyomi: 'ドン', kunyomi: 'くも-る', meaning: 'cloudy weather' },
    { kanji: '雷', onyomi: 'ライ', kunyomi: 'かみなり', meaning: 'thunder' },
    { kanji: '霜', onyomi: 'ソウ', kunyomi: 'しも', meaning: 'frost' },
    { kanji: '冬', onyomi: 'トウ', kunyomi: 'ふゆ', meaning: 'winter' },
    { kanji: '天', onyomi: 'テン', kunyomi: 'あまつ, あめ', meaning: 'heavens' },
    { kanji: '妖', onyomi: 'ヨウ', kunyomi: 'あや-しい', meaning: 'bewitched' },
    { kanji: '沃', onyomi: 'ヨク', kunyomi: '-', meaning: 'irrigate' },
    { kanji: '橋', onyomi: 'キョウ', kunyomi: 'はし', meaning: 'bridge' },
    { kanji: '嬌', onyomi: 'キョウ', kunyomi: '-', meaning: 'attractive' },
    { kanji: '立', onyomi: 'リツ, リュウ', kunyomi: 'た-つ, た-てる', meaning: 'stand up' },
    { kanji: '泣', onyomi: 'キュウ', kunyomi: 'な-く', meaning: 'cry' },
    { kanji: '章', onyomi: 'ショウ', kunyomi: '-', meaning: 'badge' },
    { kanji: '競', onyomi: 'キョウ, ケイ', kunyomi: 'きそ-う, せ-る', meaning: 'vie' },
    { kanji: '帝', onyomi: 'テイ', kunyomi: '-', meaning: 'sovereign' },
    { kanji: '諦', onyomi: 'テイ', kunyomi: '-', meaning: 'renunciation' },
    { kanji: '童', onyomi: 'ドウ', kunyomi: 'わらべ', meaning: 'juvenile' },
    { kanji: '瞳', onyomi: 'ドウ', kunyomi: 'ひとみ', meaning: 'pupil' }
];
export const chapter18c = [
    { kanji: '鐘', onyomi: 'ショウ', kunyomi: 'かね', meaning: 'bell' },
    { kanji: '商', onyomi: 'ショウ', kunyomi: 'あきな-う', meaning: 'make a deal' },
    { kanji: '嫡', onyomi: 'チャク', kunyomi: '-', meaning: 'legitimate wife' },
    { kanji: '適', onyomi: 'テキ', kunyomi: 'かな-う', meaning: 'suitable' },
    { kanji: '滴', onyomi: 'テキ', kunyomi: 'しずく, したた-る', meaning: 'drip' },
    { kanji: '敵', onyomi: 'テキ', kunyomi: 'かたき', meaning: 'enemy' },
    { kanji: '匕', onyomi: 'ヒ', kunyomi: '-', meaning: 'spoon' },
    { kanji: '叱', onyomi: 'シツ', kunyomi: 'しか-る', meaning: 'scold' },
    { kanji: '匂', onyomi: 'ヒ', kunyomi: 'にお-う', meaning: 'aroma' },
    { kanji: '頃', onyomi: 'ケイ', kunyomi: 'ころ', meaning: 'about that time' },
    { kanji: '北', onyomi: 'ホク', kunyomi: 'きた', meaning: 'north' },
    { kanji: '背', onyomi: 'ハイ', kunyomi: 'せ, せい', meaning: 'stature' },
    { kanji: '比', onyomi: 'ヒ', kunyomi: 'くら-べる', meaning: 'compare' },
    { kanji: '昆', onyomi: 'コン', kunyomi: '-', meaning: 'descendants' },
    { kanji: '皆', onyomi: 'カイ', kunyomi: 'みな', meaning: 'all' },
    { kanji: '楷', onyomi: 'カイ', kunyomi: '-', meaning: 'block letters' },
    { kanji: '諧', onyomi: 'カイ', kunyomi: '-', meaning: 'orderliness' },
    { kanji: '混', onyomi: 'コン', kunyomi: 'ま-じる, ま-ざる, ま-ぜる, こ-む', meaning: 'mix' },
    { kanji: '渇', onyomi: 'カツ', kunyomi: 'かわ-く', meaning: 'thirst' },
    { kanji: '謁', onyomi: 'エツ', kunyomi: '-', meaning: 'audience' },
    { kanji: '褐', onyomi: 'カツ', kunyomi: '-', meaning: 'brown' },
    { kanji: '喝', onyomi: 'カツ', kunyomi: '-', meaning: 'hoarse' },
    { kanji: '葛', onyomi: 'カツ', kunyomi: 'くず', meaning: 'kudzu' },
    { kanji: '旨', onyomi: 'シ', kunyomi: 'むね', meaning: 'delicious' }
];
