export const chapter19 = [
    { kanji: '賠', onyomi: 'バイ', kunyomi: '-', meaning: 'compensation' },
    { kanji: '培', onyomi: 'バイ', kunyomi: 'つちか-う', meaning: 'cultivate' },
    { kanji: '剖', onyomi: 'ボウ', kunyomi: 'わ-く', meaning: 'divide' },
    { kanji: '音', onyomi: 'オン', kunyomi: 'おと', meaning: 'sound' },
    { kanji: '韻', onyomi: 'イン', kunyomi: 'いん', meaning: 'rhyme' },
    { kanji: '識', onyomi: 'シキ', kunyomi: 'し-る', meaning: 'knowledge/awareness discrimination' },
    { kanji: '鏡', onyomi: 'キョウ', kunyomi: 'かがみ', meaning: 'mirror' },
    { kanji: '境', onyomi: 'キョウ', kunyomi: 'さかい', meaning: 'boundary' },
    { kanji: '亡', onyomi: 'ボウ', kunyomi: 'な-い', meaning: 'deceased' },
    { kanji: '妄', onyomi: 'モウ', kunyomi: 'みだ-り', meaning: 'delusion' },
    { kanji: '荒', onyomi: 'コウ', kunyomi: 'あら-い', meaning: 'laid waste, wild, rough' },
    { kanji: '望', onyomi: 'ボウ', kunyomi: 'のぞ-む', meaning: 'ambition' },
    { kanji: '方', onyomi: 'ホウ', kunyomi: 'かた', meaning: 'direction' },
    { kanji: '妨', onyomi: 'ボウ', kunyomi: 'さまた-げる', meaning: 'disturb' },
    { kanji: '坊', onyomi: 'ボウ', kunyomi: 'ぼう', meaning: 'boy' },
    { kanji: '芳', onyomi: 'ホウ', kunyomi: 'かんば-しい', meaning: 'perfumed' },
    { kanji: '肪', onyomi: 'ボウ', kunyomi: 'あぶら', meaning: 'obese' },
    { kanji: '訪', onyomi: 'ホウ', kunyomi: 'おとず-れる', meaning: 'call on, visit' },
    { kanji: '放', onyomi: 'ホウ', kunyomi: 'はな-す', meaning: 'set free, release, let go' },
    { kanji: '激', onyomi: 'ゲキ', kunyomi: 'はげ-しい', meaning: 'violent' },
    { kanji: '脱', onyomi: 'ダツ', kunyomi: 'ぬ-ぐ', meaning: 'undress, remove, escape' },
    { kanji: '説', onyomi: 'セツ', kunyomi: 'と-く', meaning: 'explanation theory' },
    { kanji: '鋭', onyomi: 'エイ', kunyomi: 'するど-い', meaning: 'pointed, sharp' },
    { kanji: '曽', onyomi: 'ソウ', kunyomi: 'かつて', meaning: 'formerly, once' },
    { kanji: '増', onyomi: 'ゾウ', kunyomi: 'ま-す', meaning: 'increase, add' },
    { kanji: '贈', onyomi: 'ゾウ', kunyomi: 'おく-る', meaning: 'presents, give' },
    { kanji: '東', onyomi: 'トウ', kunyomi: 'ひがし', meaning: 'east' },
    { kanji: '棟', onyomi: 'トウ', kunyomi: 'むね', meaning: 'ridgepole (of a roof)' },
    { kanji: '凍', onyomi: 'トウ', kunyomi: 'こお-る', meaning: 'frozen' },
    { kanji: '妊', onyomi: 'ニン', kunyomi: 'みごも-る', meaning: 'pregnancy' },
    { kanji: '廷', onyomi: 'テイ', kunyomi: '-', meaning: 'courts (royal court or courtyard)' },
];
