export const chapter21a = [
    { kanji: '地', onyomi: 'チ', kunyomi: 'じ', meaning: 'ground' },
    { kanji: '池', onyomi: 'チ', kunyomi: 'いけ', meaning: 'pond' },
    { kanji: '虫', onyomi: 'チュウ', kunyomi: 'むし', meaning: 'insect' },
    { kanji: '蛍', onyomi: 'ケイ', kunyomi: 'ほたる', meaning: 'lightning bug' },
    { kanji: '蛇', onyomi: 'ジャ', kunyomi: 'へび', meaning: 'snake' },
    { kanji: '虹', onyomi: 'コウ', kunyomi: 'にじ', meaning: 'rainbow' },
    { kanji: '蝶', onyomi: 'チョウ', kunyomi: 'ちょう', meaning: 'butterfly' },
    { kanji: '独', onyomi: 'ドク', kunyomi: 'ひと-り', meaning: 'single, alone' },
    { kanji: '蚕', onyomi: 'サン', kunyomi: 'かいこ', meaning: 'silkworm' },
    { kanji: '風', onyomi: 'フウ', kunyomi: 'かぜ', meaning: 'wind' },
    { kanji: '己', onyomi: 'コ', kunyomi: 'おのれ', meaning: 'self' },
    { kanji: '起', onyomi: 'キ', kunyomi: 'お-きる', meaning: 'rouse, wake up' },
    { kanji: '妃', onyomi: 'ヒ', kunyomi: 'きさき', meaning: 'queen' },
    { kanji: '改', onyomi: 'カイ', kunyomi: 'あらた-める', meaning: 'reformation, change' },
    { kanji: '記', onyomi: 'キ', kunyomi: 'しるし', meaning: 'scribe' },
    { kanji: '包', onyomi: 'ホウ', kunyomi: 'つつ-む', meaning: 'wrap' },
    { kanji: '胞', onyomi: 'ホウ', kunyomi: '-', meaning: 'placenta' },
    { kanji: '砲', onyomi: 'ホウ', kunyomi: 'ほう', meaning: 'cannon' },
    { kanji: '泡', onyomi: 'ホウ', kunyomi: 'あわ', meaning: 'bubble' },
    { kanji: '亀', onyomi: 'キ', kunyomi: 'かめ', meaning: 'tortoise' },
    { kanji: '電', onyomi: 'デン', kunyomi: '-', meaning: 'electricity' },
    { kanji: '竜', onyomi: 'リュウ', kunyomi: 'たつ', meaning: 'dragon' },
    { kanji: '滝', onyomi: 'ロウ', kunyomi: 'たき', meaning: 'waterfall' },
    { kanji: '豚', onyomi: 'トン', kunyomi: 'ぶた', meaning: 'pork' },
    { kanji: '逐', onyomi: 'チク', kunyomi: 'お-う', meaning: 'pursue' },
    { kanji: '遂', onyomi: 'スイ', kunyomi: 'と-げる', meaning: 'consummate, accomplish' },
    { kanji: '家', onyomi: 'カ', kunyomi: 'いえ', meaning: 'house' },
    { kanji: '嫁', onyomi: 'カ', kunyomi: 'よめ', meaning: 'marry into' },
    { kanji: '豪', onyomi: 'ゴウ', kunyomi: 'えら-い', meaning: 'overpowering' },
    { kanji: '腸', onyomi: 'チョウ', kunyomi: 'はらわた', meaning: 'intestines' },
    { kanji: '場', onyomi: 'ジョウ', kunyomi: 'ば', meaning: 'location' },
    { kanji: '湯', onyomi: 'トウ', kunyomi: 'ゆ', meaning: 'hot water' },
];

export const chapter21b = [
    { kanji: '羊', onyomi: 'ヨウ', kunyomi: 'ひつじ', meaning: 'sheep' },
    { kanji: '美', onyomi: 'ビ', kunyomi: 'うつく-しい', meaning: 'beauty' },
    { kanji: '洋', onyomi: 'ヨウ', kunyomi: '-', meaning: 'ocean' },
    { kanji: '詳', onyomi: 'ショウ', kunyomi: 'くわ-しい', meaning: 'detailed' },
    { kanji: '鮮', onyomi: 'セン', kunyomi: 'あざ-やか', meaning: 'fresh' },
    { kanji: '達', onyomi: 'タツ', kunyomi: 'たっ-する', meaning: 'accomplished' },
    { kanji: '羨', onyomi: 'セン', kunyomi: 'うらや-む', meaning: 'envious' },
    { kanji: '差', onyomi: 'サ', kunyomi: 'さ-す', meaning: 'distinction, difference' },
    { kanji: '着', onyomi: 'チャク', kunyomi: 'き-る', meaning: 'wear, put on' },
    { kanji: '唯', onyomi: 'ユイ', kunyomi: 'た-だ', meaning: 'solely, merely' },
    { kanji: '堆', onyomi: 'タイ', kunyomi: 'うずたか-い', meaning: 'piled high' },
    { kanji: '椎', onyomi: 'ツイ', kunyomi: 'しい', meaning: 'sweet oak' },
    { kanji: '誰', onyomi: 'スイ', kunyomi: 'だれ', meaning: 'who?' },
    { kanji: '焦', onyomi: 'ショウ', kunyomi: 'こ-げる', meaning: 'char, scorch' },
    { kanji: '礁', onyomi: 'ショウ', kunyomi: '-', meaning: 'reef' },
    { kanji: '集', onyomi: 'シュウ', kunyomi: 'あつ-まる', meaning: 'gather' },
    { kanji: '准', onyomi: 'ジュン', kunyomi: '-', meaning: 'quasi-' },
    { kanji: '進', onyomi: 'シン', kunyomi: 'すす-む', meaning: 'advance' },
    { kanji: '雑', onyomi: 'ザツ', kunyomi: 'まじ-える', meaning: 'miscellaneous' },
    { kanji: '雌', onyomi: 'シ', kunyomi: 'め, めす', meaning: 'female, feminine' },
    { kanji: '準', onyomi: 'ジュン', kunyomi: '-', meaning: 'semi-' },
    { kanji: '奮', onyomi: 'フン', kunyomi: 'ふる-う', meaning: 'stirred up' },
    { kanji: '奪', onyomi: 'ダツ', kunyomi: 'うば-う', meaning: 'rob' },
    { kanji: '確', onyomi: 'カク', kunyomi: 'たし-か', meaning: 'assurance, certain' },
    { kanji: '午', onyomi: 'ゴ', kunyomi: 'うま', meaning: 'noon' },
    { kanji: '許', onyomi: 'キョ', kunyomi: 'ゆる-す', meaning: 'permit' },
    { kanji: '歓', onyomi: 'カン', kunyomi: 'よろこ-ぶ', meaning: 'delight' },
    { kanji: '権', onyomi: 'ケン', kunyomi: 'おもん', meaning: 'authority' },
    { kanji: '観', onyomi: 'カン', kunyomi: 'みる', meaning: 'outlook' },
    { kanji: '羽', onyomi: 'ウ', kunyomi: 'はね', meaning: 'feathers' },
    { kanji: '習', onyomi: 'シュウ', kunyomi: 'なら-う', meaning: 'learn' },
    { kanji: '翌', onyomi: 'ヨク', kunyomi: 'あくる', meaning: 'the following' },
    { kanji: '曜', onyomi: 'ヨウ', kunyomi: '-', meaning: 'weekday' },
    { kanji: '濯', onyomi: 'タク', kunyomi: 'すす-ぐ', meaning: 'laundry' },
];
