export const chapter22a = [
    { kanji: '曰', onyomi: '', kunyomi: '', meaning: 'sayeth, to call' },
    { kanji: '困', onyomi: '', kunyomi: '', meaning: 'quandary, be distressed' },
    { kanji: '固', onyomi: '', kunyomi: '', meaning: 'harden' },
    { kanji: '錮', onyomi: '', kunyomi: '', meaning: 'weld, to bind, restrict' },
    { kanji: '国', onyomi: '', kunyomi: '', meaning: 'country' },
    { kanji: '団', onyomi: '', kunyomi: '', meaning: 'group' },
    { kanji: '因', onyomi: '', kunyomi: '', meaning: 'cause' },
    { kanji: '姻', onyomi: '', kunyomi: '', meaning: 'matrimony' },
    { kanji: '咽', onyomi: '', kunyomi: '', meaning: 'windpipe' },
    { kanji: '園', onyomi: '', kunyomi: '', meaning: 'park' },
    { kanji: '回', onyomi: '', kunyomi: '', meaning: '-times' },
    { kanji: '壇', onyomi: '', kunyomi: '', meaning: 'podium' },
    { kanji: '店', onyomi: '', kunyomi: '', meaning: 'store' },
    { kanji: '庫', onyomi: '', kunyomi: '', meaning: 'warehouse' },
    { kanji: '庭', onyomi: '', kunyomi: '', meaning: 'courtyard' },
    { kanji: '庁', onyomi: '', kunyomi: '', meaning: 'government office' },
    { kanji: '床', onyomi: '', kunyomi: '', meaning: 'bed' },
    { kanji: '麻', onyomi: '', kunyomi: '', meaning: 'hemp' },
    { kanji: '磨', onyomi: '', kunyomi: '', meaning: 'grind' },
    { kanji: '心', onyomi: '', kunyomi: '', meaning: 'heart' },
    { kanji: '忘', onyomi: '', kunyomi: '', meaning: 'forget' },
    { kanji: '恣', onyomi: '', kunyomi: '', meaning: 'selfish' },
    { kanji: '忍', onyomi: '', kunyomi: '', meaning: 'endure' },
    { kanji: '認', onyomi: '', kunyomi: '', meaning: 'acknowledge, recognize' },
    { kanji: '忌', onyomi: '', kunyomi: '', meaning: 'mourning' },
    { kanji: '志', onyomi: '', kunyomi: '', meaning: 'intention' },
    { kanji: '誌', onyomi: '', kunyomi: '', meaning: 'document' },
    { kanji: '芯', onyomi: '', kunyomi: '', meaning: 'wick' },
    { kanji: '忠', onyomi: '', kunyomi: '', meaning: 'loyalty' },
    { kanji: '串', onyomi: '', kunyomi: '', meaning: 'shish kebab, skewer' },
    { kanji: '患', onyomi: '', kunyomi: '', meaning: 'afflicted' },
    { kanji: '思', onyomi: '', kunyomi: '', meaning: 'think' },
    { kanji: '恩', onyomi: '', kunyomi: '', meaning: 'grace, kindness' },
    { kanji: '応', onyomi: '', kunyomi: '', meaning: 'apply' },
    { kanji: '意', onyomi: '', kunyomi: '', meaning: 'idea' },
    { kanji: '臆', onyomi: '', kunyomi: '', meaning: 'cowardice' },
];

export const chapter22b = [
    { kanji: '想', onyomi: '', kunyomi: '', meaning: 'concept' },
    { kanji: '息', onyomi: '', kunyomi: '', meaning: 'breath' },
    { kanji: '憩', onyomi: '', kunyomi: '', meaning: 'recess, rest' },
    { kanji: '恵', onyomi: '', kunyomi: '', meaning: 'favor' },
    { kanji: '恐', onyomi: '', kunyomi: '', meaning: 'fear' },
    { kanji: '惑', onyomi: '', kunyomi: '', meaning: 'perplex' },
    { kanji: '感', onyomi: '', kunyomi: '', meaning: 'emotion' },
    { kanji: '憂', onyomi: '', kunyomi: '', meaning: 'melancholy' },
    { kanji: '寡', onyomi: '', kunyomi: '', meaning: 'widow' },
    { kanji: '忙', onyomi: '', kunyomi: '', meaning: 'busy' },
    { kanji: '悦', onyomi: '', kunyomi: '', meaning: 'ecstasy' },
    { kanji: '恒', onyomi: '', kunyomi: '', meaning: 'constancy, always' },
    { kanji: '悼', onyomi: '', kunyomi: '', meaning: 'lament, grieve over' },
    { kanji: '悟', onyomi: '', kunyomi: '', meaning: 'enlightenment' },
    { kanji: '怖', onyomi: '', kunyomi: '', meaning: 'dreadful' },
    { kanji: '慌', onyomi: '', kunyomi: '', meaning: 'disconcerted, be confused' },
    { kanji: '悔', onyomi: '', kunyomi: '', meaning: 'repent, regret' },
    { kanji: '憎', onyomi: '', kunyomi: '', meaning: 'hate' },
    { kanji: '慣', onyomi: '', kunyomi: '', meaning: 'accustomed' },
    { kanji: '愉', onyomi: '', kunyomi: '', meaning: 'pleasure' },
    { kanji: '惰', onyomi: '', kunyomi: '', meaning: 'lazy' },
    { kanji: '慎', onyomi: '', kunyomi: '', meaning: 'humility' },
    { kanji: '憾', onyomi: '', kunyomi: '', meaning: 'remorse' },
    { kanji: '憶', onyomi: '', kunyomi: '', meaning: 'recollection' },
    { kanji: '惧', onyomi: '', kunyomi: '', meaning: 'disquieting, feeling of anxiety' },
    { kanji: '憧', onyomi: '', kunyomi: '', meaning: 'yearn, long for' },
    { kanji: '憬', onyomi: '', kunyomi: '', meaning: 'hanker, yearn to do something' },
    { kanji: '慕', onyomi: '', kunyomi: '', meaning: 'long for, pine for, love' },
    { kanji: '添', onyomi: '', kunyomi: '', meaning: 'annexed' },
    { kanji: '必', onyomi: '', kunyomi: '', meaning: 'invariably, certain' },
    { kanji: '泌', onyomi: '', kunyomi: '', meaning: 'ooze' },
];
