export const chapter23a = [
    { kanji: '手', onyomi: '', kunyomi: '', meaning: 'hand' },
    { kanji: '看', onyomi: '', kunyomi: '', meaning: 'watch over' },
    { kanji: '摩', onyomi: '', kunyomi: '', meaning: 'chafe, rub' },
    { kanji: '我', onyomi: '', kunyomi: '', meaning: 'ego' },
    { kanji: '義', onyomi: '', kunyomi: '', meaning: 'righteousness' },
    { kanji: '議', onyomi: '', kunyomi: '', meaning: 'deliberation, long consideration' },
    { kanji: '犠', onyomi: '', kunyomi: '', meaning: 'sacrifice' },
    { kanji: '抹', onyomi: '', kunyomi: '', meaning: 'rub' },
    { kanji: '拭', onyomi: '', kunyomi: '', meaning: 'wipe' },
    { kanji: '拉', onyomi: '', kunyomi: '', meaning: 'yank' },
    { kanji: '抱', onyomi: '', kunyomi: '', meaning: 'embrace' },
    { kanji: '搭', onyomi: '', kunyomi: '', meaning: 'board' },
    { kanji: '抄', onyomi: '', kunyomi: '', meaning: 'extract' },
    { kanji: '抗', onyomi: '', kunyomi: '', meaning: 'confront' },
    { kanji: '批', onyomi: '', kunyomi: '', meaning: 'criticism' },
    { kanji: '招', onyomi: '', kunyomi: '', meaning: 'beckon' },
    { kanji: '拓', onyomi: '', kunyomi: '', meaning: 'clear the land' },
    { kanji: '拍', onyomi: '', kunyomi: '', meaning: 'clap' },
    { kanji: '打', onyomi: '', kunyomi: '', meaning: 'strike' },
    { kanji: '拘', onyomi: '', kunyomi: '', meaning: 'arrest' },
    { kanji: '捨', onyomi: '', kunyomi: '', meaning: 'discard' },
    { kanji: '拐', onyomi: '', kunyomi: '', meaning: 'kidnap' },
    { kanji: '摘', onyomi: '', kunyomi: '', meaning: 'pinch' },
    { kanji: '挑', onyomi: '', kunyomi: '', meaning: 'challenge' },
];
export const chapter23b = [
    { kanji: '指', onyomi: '', kunyomi: '', meaning: 'finger' },
    { kanji: '持', onyomi: '', kunyomi: '', meaning: 'hold' },
    { kanji: '拶', onyomi: '', kunyomi: '', meaning: 'imminent' },
    { kanji: '括', onyomi: '', kunyomi: '', meaning: 'fasten' },
    { kanji: '揮', onyomi: '', kunyomi: '', meaning: 'brandish, wave, wag, swing' },
    { kanji: '推', onyomi: '', kunyomi: '', meaning: 'conjecture, speculation based on incomplete information' },
    { kanji: '揚', onyomi: '', kunyomi: '', meaning: 'hoist, raise' },
    { kanji: '提', onyomi: '', kunyomi: '', meaning: 'propose' },
    { kanji: '損', onyomi: '', kunyomi: '', meaning: 'damage' },
    { kanji: '拾', onyomi: '', kunyomi: '', meaning: 'pick up' },
    { kanji: '担', onyomi: '', kunyomi: '', meaning: 'shouldering, bearing' },
    { kanji: '拠', onyomi: '', kunyomi: '', meaning: 'foothold' },
    { kanji: '描', onyomi: '', kunyomi: '', meaning: 'sketch' },
    { kanji: '操', onyomi: '', kunyomi: '', meaning: 'maneuver' },
    { kanji: '接', onyomi: '', kunyomi: '', meaning: 'touch' },
    { kanji: '掲', onyomi: '', kunyomi: '', meaning: 'put up a notice' },
    { kanji: '掛', onyomi: '', kunyomi: '', meaning: 'hang' },
    { kanji: '捗', onyomi: '', kunyomi: '', meaning: 'make headway, make progress' },
    { kanji: '研', onyomi: '', kunyomi: '', meaning: 'polish' },
    { kanji: '戒', onyomi: '', kunyomi: '', meaning: 'commandment' },
    { kanji: '弄', onyomi: '', kunyomi: '', meaning: 'tinker with' },
    { kanji: '械', onyomi: '', kunyomi: '', meaning: 'contraption' },
    { kanji: '鼻', onyomi: '', kunyomi: '', meaning: 'nose' },
    { kanji: '刑', onyomi: '', kunyomi: '', meaning: 'punish' },
];
export const chapter23c = [
    { kanji: '型', onyomi: '', kunyomi: '', meaning: 'mould' },
    { kanji: '才', onyomi: '', kunyomi: '', meaning: 'genius' },
    { kanji: '財', onyomi: '', kunyomi: '', meaning: 'property, money, wealth' },
    { kanji: '材', onyomi: '', kunyomi: '', meaning: 'lumber' },
    { kanji: '存', onyomi: '', kunyomi: '', meaning: 'exist, suppose' },
    { kanji: '在', onyomi: '', kunyomi: '', meaning: 'exist' },
    { kanji: '乃', onyomi: '', kunyomi: '', meaning: 'from' },
    { kanji: '携', onyomi: '', kunyomi: '', meaning: 'portable' },
    { kanji: '及', onyomi: '', kunyomi: '', meaning: 'reach out' },
    { kanji: '吸', onyomi: '', kunyomi: '', meaning: 'suck' },
    { kanji: '扱', onyomi: '', kunyomi: '', meaning: 'handle' },
    { kanji: '丈', onyomi: '', kunyomi: '', meaning: 'length' },
    { kanji: '史', onyomi: '', kunyomi: '', meaning: 'history' },
    { kanji: '吏', onyomi: '', kunyomi: '', meaning: 'officer' },
    { kanji: '更', onyomi: '', kunyomi: '', meaning: 'grow late' },
    { kanji: '硬', onyomi: '', kunyomi: '', meaning: 'stiff' },
    { kanji: '梗', onyomi: '', kunyomi: '', meaning: 'blockage, spiny' },
    { kanji: '又', onyomi: '', kunyomi: '', meaning: 'or again' },
    { kanji: '双', onyomi: '', kunyomi: '', meaning: 'pair' },
    { kanji: '桑', onyomi: '', kunyomi: '', meaning: 'mulberry' },
    { kanji: '隻', onyomi: '', kunyomi: '', meaning: 'vessels' },
    { kanji: '護', onyomi: '', kunyomi: '', meaning: 'safeguard' },
    { kanji: '獲', onyomi: '', kunyomi: '', meaning: 'seize' },
    { kanji: '奴', onyomi: '', kunyomi: '', meaning: 'guy' },
];
export const chapter23d = [
    { kanji: '怒', onyomi: '', kunyomi: '', meaning: 'angry' },
    { kanji: '友', onyomi: '', kunyomi: '', meaning: 'friend' },
    { kanji: '抜', onyomi: '', kunyomi: '', meaning: 'slip out' },
    { kanji: '投', onyomi: '', kunyomi: '', meaning: 'throw' },
    { kanji: '没', onyomi: '', kunyomi: '', meaning: 'drown' },
    { kanji: '股', onyomi: '', kunyomi: '', meaning: 'thigh' },
    { kanji: '設', onyomi: '', kunyomi: '', meaning: 'establishment' },
    { kanji: '撃', onyomi: '', kunyomi: '', meaning: 'beat, attack, defeat, conquer' },
    { kanji: '殻', onyomi: '', kunyomi: '', meaning: 'husk' },
    { kanji: '支', onyomi: '', kunyomi: '', meaning: 'branch' },
    { kanji: '技', onyomi: '', kunyomi: '', meaning: 'skill' },
    { kanji: '枝', onyomi: '', kunyomi: '', meaning: 'bough' },
    { kanji: '肢', onyomi: '', kunyomi: '', meaning: 'limb' },
    { kanji: '茎', onyomi: '', kunyomi: '', meaning: 'stalk, stem' },
    { kanji: '怪', onyomi: '', kunyomi: '', meaning: 'suspicious' },
    { kanji: '軽', onyomi: '', kunyomi: '', meaning: 'lightly' },
    { kanji: '叔', onyomi: '', kunyomi: '', meaning: 'uncle' },
    { kanji: '督', onyomi: '', kunyomi: '', meaning: 'coach' },
    { kanji: '寂', onyomi: '', kunyomi: '', meaning: 'loneliness' },
    { kanji: '淑', onyomi: '', kunyomi: '', meaning: 'graceful' },
    { kanji: '反', onyomi: '', kunyomi: '', meaning: 'anti-' },
    { kanji: '坂', onyomi: '', kunyomi: '', meaning: 'slope' },
    { kanji: '板', onyomi: '', kunyomi: '', meaning: 'plank' },
    { kanji: '返', onyomi: '', kunyomi: '', meaning: 'return' },
];
export const chapter23e = [
    { kanji: '販', onyomi: '', kunyomi: '', meaning: 'marketing' },
    { kanji: '爪', onyomi: '', kunyomi: '', meaning: 'claw, nail, talon' },
    { kanji: '妥', onyomi: '', kunyomi: '', meaning: 'gentle' },
    { kanji: '乳', onyomi: '', kunyomi: '', meaning: 'milk' },
    { kanji: '浮', onyomi: '', kunyomi: '', meaning: 'floating' },
    { kanji: '淫', onyomi: '', kunyomi: '', meaning: 'lewd' },
    { kanji: '将', onyomi: '', kunyomi: '', meaning: 'leader' },
    { kanji: '奨', onyomi: '', kunyomi: '', meaning: 'exhort, urge' },
    { kanji: '采', onyomi: '', kunyomi: '', meaning: 'grab' },
    { kanji: '採', onyomi: '', kunyomi: '', meaning: 'pick' },
    { kanji: '菜', onyomi: '', kunyomi: '', meaning: 'vegetable' },
    { kanji: '受', onyomi: '', kunyomi: '', meaning: 'accept' },
    { kanji: '授', onyomi: '', kunyomi: '', meaning: 'impart' },
    { kanji: '愛', onyomi: '', kunyomi: '', meaning: 'love' },
    { kanji: '曖', onyomi: '', kunyomi: '', meaning: 'unclear' },
    { kanji: '払', onyomi: '', kunyomi: '', meaning: 'pay' },
    { kanji: '広', onyomi: '', kunyomi: '', meaning: 'wide' },
    { kanji: '勾', onyomi: '', kunyomi: '', meaning: 'hooked' },
    { kanji: '拡', onyomi: '', kunyomi: '', meaning: 'broaden' },
    { kanji: '鉱', onyomi: '', kunyomi: '', meaning: 'mineral' },
    { kanji: '弁', onyomi: '', kunyomi: '', meaning: 'valve' },
    { kanji: '雄', onyomi: '', kunyomi: '', meaning: 'male' },
    { kanji: '台', onyomi: '', kunyomi: '', meaning: 'pedestal' },
    { kanji: '怠', onyomi: '', kunyomi: '', meaning: 'neglect' },
];
export const chapter23f = [
    { kanji: '治', onyomi: '', kunyomi: '', meaning: 'reign' },
    { kanji: '冶', onyomi: '', kunyomi: '', meaning: 'metallurgy' },
    { kanji: '始', onyomi: '', kunyomi: '', meaning: 'commence' },
    { kanji: '胎', onyomi: '', kunyomi: '', meaning: 'womb' },
    { kanji: '窓', onyomi: '', kunyomi: '', meaning: 'window' },
    { kanji: '去', onyomi: '', kunyomi: '', meaning: 'gone' },
    { kanji: '法', onyomi: '', kunyomi: '', meaning: 'method' },
    { kanji: '会', onyomi: '', kunyomi: '', meaning: 'meeting' },
    { kanji: '至', onyomi: '', kunyomi: '', meaning: 'climax' },
    { kanji: '室', onyomi: '', kunyomi: '', meaning: 'room' },
    { kanji: '到', onyomi: '', kunyomi: '', meaning: 'arrival' },
    { kanji: '致', onyomi: '', kunyomi: '', meaning: 'doth' },
    { kanji: '互', onyomi: '', kunyomi: '', meaning: 'mutually' },
    { kanji: '棄', onyomi: '', kunyomi: '', meaning: 'abandon' },
    { kanji: '育', onyomi: '', kunyomi: '', meaning: 'bring up' },
    { kanji: '撤', onyomi: '', kunyomi: '', meaning: 'remove' },
    { kanji: '充', onyomi: '', kunyomi: '', meaning: 'allot' },
    { kanji: '銃', onyomi: '', kunyomi: '', meaning: 'gun' },
    { kanji: '硫', onyomi: '', kunyomi: '', meaning: 'sulfur' },
    { kanji: '流', onyomi: '', kunyomi: '', meaning: 'current' },
    { kanji: '允', onyomi: '', kunyomi: '', meaning: 'license' },
    { kanji: '唆', onyomi: '', kunyomi: '', meaning: 'tempt' },
];
