import { Kanji } from "../model/Kanji";

export const chapter12: Kanji[] = [
    { kanji: '介', onyomi: 'カイ', kunyomi: '', meaning: 'jammed in' },
    { kanji: '界', onyomi: 'カイ', kunyomi: '', meaning: 'world' },
    { kanji: '茶', onyomi: 'チャ', kunyomi: '', meaning: 'tea' },
    { kanji: '脊', onyomi: 'セキ', kunyomi: 'せ', meaning: 'spinal column' },
    { kanji: '合', onyomi: 'ゴウ', kunyomi: 'あ-う', meaning: 'fit' },
    { kanji: '塔', onyomi: 'トウ', kunyomi: '', meaning: 'pagoda' },
    { kanji: '王', onyomi: 'オウ', kunyomi: '', meaning: 'king' },
    { kanji: '玉', onyomi: 'ギョク', kunyomi: 'たま', meaning: 'jewel' },
    { kanji: '宝', onyomi: 'ホウ', kunyomi: 'たから', meaning: 'treasure' },
    { kanji: '珠', onyomi: 'シュ', kunyomi: 'たま', meaning: 'pearl' },
    { kanji: '現', onyomi: 'ゲン', kunyomi: 'あらわ-れる', meaning: 'present' },
    { kanji: '玩', onyomi: 'ガン', kunyomi: 'もちあそ-ぶ', meaning: 'toy' },
    { kanji: '狂', onyomi: 'キョウ', kunyomi: 'くる-う', meaning: 'lunatic' },
    { kanji: '旺', onyomi: 'オウ', kunyomi: '', meaning: 'effulgent' },
    { kanji: '皇', onyomi: 'コウ', kunyomi: '', meaning: 'emperor' },
    { kanji: '呈', onyomi: 'テイ', kunyomi: 'あらわ-す', meaning: 'display' },
    { kanji: '全', onyomi: 'ゼン', kunyomi: 'まった-く', meaning: 'whole' },
    { kanji: '栓', onyomi: 'セン', kunyomi: 'しめ-る', meaning: 'plug' },
    { kanji: '理', onyomi: 'リ', kunyomi: 'ことわり', meaning: 'logic' },
    { kanji: '主', onyomi: 'シュ', kunyomi: 'ぬし', meaning: 'lord' },
    { kanji: '注', onyomi: 'チュウ', kunyomi: 'そそ-ぐ', meaning: 'pour' },
    { kanji: '柱', onyomi: 'チュウ', kunyomi: 'はしら', meaning: 'pillar' },
    { kanji: '金', onyomi: 'キン', kunyomi: 'かね', meaning: 'gold' },
    { kanji: '銑', onyomi: 'セン', kunyomi: '', meaning: 'pig iron' },
    { kanji: '鉢', onyomi: 'ハチ', kunyomi: '', meaning: 'bowl' },
    { kanji: '銅', onyomi: 'ドウ', kunyomi: 'あかがね', meaning: 'copper' },
    { kanji: '釣', onyomi: 'チョウ', kunyomi: 'つ-る', meaning: 'angling' },
    { kanji: '針', onyomi: 'シン', kunyomi: 'はり', meaning: 'needle' },
    { kanji: '銘', onyomi: 'メイ', kunyomi: 'な', meaning: 'inscription' },
    { kanji: '鎮', onyomi: 'チン', kunyomi: 'しず-める', meaning: 'tranquilize' }
];
