export const chapter18a = [
    { kanji: '衣', onyomi: 'イ', kunyomi: 'ころも', meaning: 'garment' },
    { kanji: '裁', onyomi: 'サイ', kunyomi: 'た-つ', meaning: 'tailor' },
    { kanji: '装', onyomi: 'ソウ', kunyomi: 'よそお-う', meaning: 'attire' },
    { kanji: '裏', onyomi: 'リ', kunyomi: 'うら', meaning: 'back' },
    { kanji: '壊', onyomi: 'カイ', kunyomi: 'こわ-す', meaning: 'demolition' },
    { kanji: '哀', onyomi: 'アイ', kunyomi: 'あわ-れ', meaning: 'pathetic' },
    { kanji: '遠', onyomi: 'エン', kunyomi: 'とお-い', meaning: 'distant' },
    { kanji: '猿', onyomi: 'エン', kunyomi: 'さる', meaning: 'monkey' },
    { kanji: '初', onyomi: 'ショ', kunyomi: 'はじ-め', meaning: 'first time' },
    { kanji: '巾', onyomi: 'キン', kunyomi: 'はば', meaning: 'towel' },
    { kanji: '布', onyomi: 'フ', kunyomi: 'ぬの', meaning: 'linen' },
    { kanji: '帆', onyomi: 'ハン', kunyomi: 'ほ', meaning: 'sail' },
    { kanji: '幅', onyomi: 'フク', kunyomi: 'はば', meaning: 'hanging scroll' },
    { kanji: '帽', onyomi: 'ボウ', kunyomi: 'ずきん', meaning: 'cap' },
    { kanji: '幕', onyomi: 'マク', kunyomi: 'とばり', meaning: 'curtain' },
    { kanji: '幌', onyomi: 'コウ', kunyomi: 'ほろ', meaning: 'canopy' },
    { kanji: '錦', onyomi: 'キン', kunyomi: 'にしき', meaning: 'brocade' },
    { kanji: '市', onyomi: 'シ', kunyomi: 'いち', meaning: 'market' },
    { kanji: '柿', onyomi: 'シ', kunyomi: 'かき', meaning: 'persimmon' },
    { kanji: '姉', onyomi: 'シ', kunyomi: 'あね', meaning: 'elder sister' },
    { kanji: '肺', onyomi: 'ハイ', kunyomi: 'はい', meaning: 'lungs' },
];
