export const chapter18b = [
    { kanji: '帯', onyomi: 'タイ', kunyomi: '-', meaning: 'sash' },
    { kanji: '滞', onyomi: 'タイ', kunyomi: 'とどこお-る', meaning: 'stagnate' },
    { kanji: '刺', onyomi: 'シ', kunyomi: 'さ-す, さ-さる', meaning: 'thorn' },
    { kanji: '制', onyomi: 'セイ', kunyomi: '-', meaning: 'system' },
    { kanji: '製', onyomi: 'セイ', kunyomi: '-', meaning: 'made in...' },
    { kanji: '転', onyomi: 'テン', kunyomi: 'ころ-がる, ころ-げる', meaning: 'revolve' },
    { kanji: '芸', onyomi: 'ゲイ', kunyomi: '-', meaning: 'technique' },
    { kanji: '雨', onyomi: 'ウ', kunyomi: 'あめ, あま-', meaning: 'rain' },
    { kanji: '雲', onyomi: 'ウン', kunyomi: 'くも', meaning: 'cloud' },
    { kanji: '曇', onyomi: 'ドン', kunyomi: 'くも-る', meaning: 'cloudy weather' },
    { kanji: '雷', onyomi: 'ライ', kunyomi: 'かみなり', meaning: 'thunder' },
    { kanji: '霜', onyomi: 'ソウ', kunyomi: 'しも', meaning: 'frost' },
    { kanji: '冬', onyomi: 'トウ', kunyomi: 'ふゆ', meaning: 'winter' },
    { kanji: '天', onyomi: 'テン', kunyomi: 'あまつ, あめ', meaning: 'heavens' },
    { kanji: '妖', onyomi: 'ヨウ', kunyomi: 'あや-しい', meaning: 'bewitched' },
    { kanji: '沃', onyomi: 'ヨク', kunyomi: '-', meaning: 'irrigate' },
    { kanji: '橋', onyomi: 'キョウ', kunyomi: 'はし', meaning: 'bridge' },
    { kanji: '嬌', onyomi: 'キョウ', kunyomi: '-', meaning: 'attractive' },
    { kanji: '立', onyomi: 'リツ, リュウ', kunyomi: 'た-つ, た-てる', meaning: 'stand up' },
    { kanji: '泣', onyomi: 'キュウ', kunyomi: 'な-く', meaning: 'cry' },
    { kanji: '章', onyomi: 'ショウ', kunyomi: '-', meaning: 'badge' },
    { kanji: '競', onyomi: 'キョウ, ケイ', kunyomi: 'きそ-う, せ-る', meaning: 'vie' },
    { kanji: '帝', onyomi: 'テイ', kunyomi: '-', meaning: 'sovereign' },
    { kanji: '諦', onyomi: 'テイ', kunyomi: '-', meaning: 'renunciation' },
    { kanji: '童', onyomi: 'ドウ', kunyomi: 'わらべ', meaning: 'juvenile' },
    { kanji: '瞳', onyomi: 'ドウ', kunyomi: 'ひとみ', meaning: 'pupil' }
];
