import { Kanji } from "../model/Kanji";

export const chapter7: Kanji[] = [
    { kanji: '小', onyomi: 'ショウ', kunyomi: 'ちい-さい', meaning: 'little' },
    { kanji: '少', onyomi: 'ショウ', kunyomi: 'すく-ない', meaning: 'few' },
    { kanji: '大', onyomi: 'ダイ・タイ', kunyomi: 'おお-きい', meaning: 'large' },
    { kanji: '多', onyomi: 'タ', kunyomi: 'おお-い', meaning: 'many' },
    { kanji: '夕', onyomi: 'セキ', kunyomi: 'ゆう', meaning: 'evening' },
    { kanji: '汐', onyomi: 'セキ', kunyomi: 'しお', meaning: 'eventide' },
    { kanji: '外', onyomi: 'ガイ・ゲ', kunyomi: 'そと・ほか・はず-す・はず-れる', meaning: 'outside' },
    { kanji: '名', onyomi: 'メイ・ミョウ', kunyomi: 'な', meaning: 'name' },
    { kanji: '石', onyomi: 'セキ・シャク・コク', kunyomi: 'いし', meaning: 'stone' },
    { kanji: '肖', onyomi: 'ショウ', kunyomi: 'あやか-る', meaning: 'resemblance' },
    { kanji: '硝', onyomi: 'ショウ', kunyomi: 'せっ-する', meaning: 'nitrate' },
    { kanji: '砕', onyomi: 'サイ', kunyomi: 'くだ-く', meaning: 'smash' },
    { kanji: '砂', onyomi: 'サ・シャ', kunyomi: 'すな', meaning: 'sand' },
    { kanji: '妬', onyomi: 'ト', kunyomi: 'ねた-む', meaning: 'jealous' },
    { kanji: '削', onyomi: 'サク', kunyomi: 'けず-る', meaning: 'plane' },
    { kanji: '光', onyomi: 'コウ', kunyomi: 'ひか-る', meaning: 'ray' },
    { kanji: '太', onyomi: 'タイ・タ', kunyomi: 'ふと-い・ふと-る', meaning: 'plump' },
    { kanji: '器', onyomi: 'キ', kunyomi: 'うつわ', meaning: 'utensil' },
    { kanji: '臭', onyomi: 'シュウ', kunyomi: 'くさ-い・にお-う', meaning: 'stinking' },
    { kanji: '嗅', onyomi: 'キュウ', kunyomi: 'か-ぐ', meaning: 'sniff' },
    { kanji: '妙', onyomi: 'ミョウ・ビョウ', kunyomi: 'たえ', meaning: 'exquisite' },
    { kanji: '省', onyomi: 'セイ・ショウ', kunyomi: 'かえり-みる・はぶ-く', meaning: 'focus' },
    { kanji: '厚', onyomi: 'コウ', kunyomi: 'あつ-い', meaning: 'thick' },
    { kanji: '奇', onyomi: 'キ', kunyomi: 'く-しき・あや-しい・くし', meaning: 'strange' },
]
