import { Kanji } from "../model/Kanji";

export const chapter8: Kanji[] = [
    { kanji: '川', onyomi: '', kunyomi: 'かわ', meaning: 'stream' },
    { kanji: '州', onyomi: 'シュウ', kunyomi: '', meaning: 'state' },
    { kanji: '順', onyomi: 'ジュン', kunyomi: '', meaning: 'obey' },
    { kanji: '水', onyomi: 'スイ', kunyomi: 'みず', meaning: 'water' },
    { kanji: '氷', onyomi: 'ヒョウ', kunyomi: 'こおり', meaning: 'icicle' },
    { kanji: '永', onyomi: 'エイ', kunyomi: 'なが-い', meaning: 'eternity' },
    { kanji: '泉', onyomi: 'セン', kunyomi: 'いずみ', meaning: 'spring' },
    { kanji: '腺', onyomi: 'セン', kunyomi: '', meaning: 'gland' },
    { kanji: '原', onyomi: 'ゲン', kunyomi: 'はら', meaning: 'meadow' },
    { kanji: '願', onyomi: 'ガン', kunyomi: 'ねが-う', meaning: 'petition' },
    { kanji: '泳', onyomi: 'エイ', kunyomi: 'およ-ぐ', meaning: 'swim' },
    { kanji: '沼', onyomi: 'ショウ', kunyomi: 'ぬま', meaning: 'marsh' },
    { kanji: '沖', onyomi: 'チュウ', kunyomi: 'おき', meaning: 'open sea' },
    { kanji: '汎', onyomi: 'ハン', kunyomi: '', meaning: 'pan-' },
    { kanji: '江', onyomi: 'コウ', kunyomi: 'え', meaning: 'creek' },
    { kanji: '汰', onyomi: 'タ', kunyomi: '', meaning: 'cleanse' },
    { kanji: '汁', onyomi: 'ジュウ', kunyomi: 'しる', meaning: 'soup' },
    { kanji: '沙', onyomi: 'サ', kunyomi: 'すな', meaning: 'grains of sand' },
    { kanji: '潮', onyomi: 'チョウ', kunyomi: 'しお', meaning: 'tide' },
    { kanji: '源', onyomi: 'ゲン', kunyomi: 'みなもと', meaning: 'source' },
    { kanji: '活', onyomi: 'カツ', kunyomi: 'い-きる', meaning: 'lively' },
    { kanji: '消', onyomi: 'ショウ', kunyomi: 'き-える', meaning: 'extinguish' },
    { kanji: '況', onyomi: 'キョウ', kunyomi: 'まし-て', meaning: 'but of course' },
    { kanji: '河', onyomi: 'カ', kunyomi: 'かわ', meaning: 'river' },
    { kanji: '泊', onyomi: 'ハク', kunyomi: 'と-まる', meaning: 'overnight' },
    { kanji: '湖', onyomi: 'コ', kunyomi: 'みずうみ', meaning: 'lake' },
    { kanji: '測', onyomi: 'ソク', kunyomi: 'はか-る', meaning: 'fathom' },
    { kanji: '土', onyomi: 'ド', kunyomi: 'つち', meaning: 'soil' },
    { kanji: '吐', onyomi: 'ト', kunyomi: 'は-く', meaning: 'spit' },
    { kanji: '圧', onyomi: 'アツ', kunyomi: '', meaning: 'pressure' },
    { kanji: '埼', onyomi: 'キ', kunyomi: 'さき', meaning: 'cape' },
    { kanji: '垣', onyomi: 'エン', kunyomi: 'かき', meaning: 'hedge' },
    { kanji: '填', onyomi: 'テン', kunyomi: 'うめ-す', meaning: 'inlay' },
    { kanji: '圭', onyomi: 'ケイ', kunyomi: '', meaning: 'squared jewel' },
    { kanji: '封', onyomi: 'フウ', kunyomi: '', meaning: 'seal' },
    { kanji: '涯', onyomi: 'ガイ', kunyomi: '', meaning: 'horizon' },
    { kanji: '寺', onyomi: 'ジ', kunyomi: 'てら', meaning: 'Buddhist temple' },
    { kanji: '時', onyomi: 'ジ', kunyomi: 'とき', meaning: 'time' },
    { kanji: '均', onyomi: 'キン', kunyomi: '', meaning: 'level' },
    { kanji: '火', onyomi: 'カ', kunyomi: 'ひ', meaning: 'fire' },
    { kanji: '炎', onyomi: 'エン', kunyomi: 'ほのお', meaning: 'inflammation' },
    { kanji: '煩', onyomi: 'ハン', kunyomi: 'わずら-う', meaning: 'anxiety' },
    { kanji: '淡', onyomi: 'タン', kunyomi: 'あわ-い', meaning: 'thin' },
    { kanji: '灯', onyomi: 'トウ', kunyomi: 'ひ', meaning: 'lamp' },
    { kanji: '畑', onyomi: 'ハタ', kunyomi: 'はたけ', meaning: 'farm' },
    { kanji: '災', onyomi: 'サイ', kunyomi: 'わざわ-い', meaning: 'disaster' },
    { kanji: '灰', onyomi: 'カイ', kunyomi: 'はい', meaning: 'ashes' },
    { kanji: '点', onyomi: 'テン', kunyomi: '', meaning: 'spot' },
    { kanji: '照', onyomi: 'ショウ', kunyomi: 'て-る', meaning: 'illuminate' },
    { kanji: '魚', onyomi: 'ギョ', kunyomi: 'さかな', meaning: 'fish' },
    { kanji: '漁', onyomi: 'ギョ', kunyomi: 'あさ-る', meaning: 'fishing' }
];
